#!/data/data/com.termux/files/usr/bin/zsh

# Aliases
alias cl='bash ~/scripts/clear.sh'
alias ex='exit'
alias upd='apt update && apt upgrade -y'
alias pku='pkg update && pkg upgrade -y'
alias ga='git add .'
alias gs='git status'
alias gc='git commit -m "File Updated"'
alias gp='git push origin main'
alias ls=lsd
alias nv=nvim
alias cpy=termux-clipboard-set
alias gl='git log --oneline --graph --decorate --all'
alias weather='curl wttr.in'
alias ping='ping -c 5 stackoverflow.com'
alias cat='bat --paging=never'
alias open='termux-open'
alias gg='bash ~/scripts/gitSync.sh'
alias ..='cd ..'            
alias ...='cd ../..'      
alias ~='cd ~'             
alias dl='cd ~/downloads'   
alias db='mysql -u root -p'
alias mdb='mariadb -u root -p'
alias l='ls -lh'
alias ll='ls -lah'
alias la='ls -a'
alias ld='ls -lhd'
alias p='pwd'
alias rm='rm -rf'
alias u='cd /data/data/com.termux/files/usr'
alias h='cd /data/data/com.termux/files/home'
alias :q='exit'
alias grep='grep --color=auto'
alias open='termux-open'
alias lc='lolcat'
alias xx='chmod +x'
alias rel='termux-reload-settings'
