# Aliases  
alias desk='tx11start --nodbus'
alias aria="aria2c -d ~/storage/shared/Movies/"  
alias gg='~/git/termux/automation/git_sync.sh'
alias cl='clear'  
alias x='exit'  
alias upd='pku'
alias pku='pkg update && pkg upgrade -y'  
alias ga='git add .'  
alias gs='git status'  
alias gp='git push origin main'  
alias ls=lsd  
alias nv=nvim  
alias cpy=termux-clipboard-set  
alias gl='git log --oneline --graph --decorate --all'  
alias weather='curl wttr.in'  
alias ping='ping -c 5 stackoverflow.com'  
alias cat='bat --paging=never'  
alias open='termux-open'  
alias ..='cd ..'              
alias ...='cd ../..'        
alias ~='cd ~'               
alias dl='cd ~/downloads'     
alias l='ls -lh'  
alias ll='ls -lah'  
alias la='ls -a'  
alias ld='ls -lhd'  
alias p='pwd'  
alias rm='rm -rf'  
alias u='cd /data/data/com.termux/files/usr'  
alias h='cd /data/data/com.termux/files/home'  
alias :q='exit'  
alias grep='grep --color=auto'  
alias open='termux-open'  
alias lc='lolcat'  
alias xx='chmod +x'  
alias rel='termux-reload-settings'  
alias weather='curl wttr.in/ramanattukara'  
alias pst='termux-clipboard-get'  
alias pdlu='proot-distro login debian --user rhythmusbyte' 
alias pdl='proot-distro login debian'
alias du='du -h --max-depth=1'  
alias df='df -h'  
alias top='htop'   
alias meminfo='free -h'  
alias myip='curl ifconfig.me'  
alias ins='apt install -y'  
alias rem='apt remove -y'  
alias clean='apt autoremove && apt clean'  
alias py=python

# Start XFCE4 Desktop
# alias desk='bash /data/data/com.termux/files/home/scripts/startdesktop.sh'
# alias xf='bash ~/scripts/start-xfce.sh'
# alias stxf='bash ~/scripts/stop-xfce.sh'
# alias xf="~/scripts/cleanupx11.sh && termux-x11 :0 -xstartup 'dbus-launch --exit-with-session xfce4-session' &"
